kafka:
  topic: pippo
  messageKey: ciao

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: gruppo1
      auto-offset-reset: earliest
#      enable-auto-commit: false
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  